### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by wdowling** [wavefrontHQ/wavefront-dropwizard-metrics-sdk-java#43]
The following links no longer exist in the Wavefront Sender section (https://github.com/wavefrontHQ/wavefront-dropwizard-metrics-sdk-java#3-set-up-a-wavefrontsender)

- https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/docs/sender.md#set-up-a-wavefrontsender
- https://github.com/wavefrontHQ/wavefront-sdk-java/blob/master/docs/sender.md#share-a-wavefrontsender

**Comment by shavidissa** [comment]
Thank you, @wdowling! Apologies for the delay in fixing this.
Fixed the link and updated the README so that the content is clear. :)

[1] https://github.com/wavefrontHQ/wavefront-dropwizard-metrics-sdk-java/pull/50 - Connect to preview 
[2] https://github.com/wavefrontHQ/wavefront-dropwizard-metrics-sdk-java/pull/51
